from toontown.coghq.SpecImports import *
from toontown.toonbase import ToontownGlobals
import random

CogParent = 1004
BattleCellId = 1

CogParent2 = 1003
BattleCellId2 = 0

BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
              BattleCellId2 : {'parentEntId': CogParent2,
                'pos': Point3(0, 0, 0)},
              }

CogData = [{"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsHard,
  'battleCell': BattleCellId,
  'pos': Point3(-3.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsMedium,
  'battleCell': BattleCellId,
  'pos': Point3(-0.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsEasy,
  'battleCell': BattleCellId,
  'pos': Point3(3.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  
  {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsMedium,
  'battleCell': BattleCellId2,
  'pos': Point3(-6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsEasy,
  'battleCell': BattleCellId2,
  'pos': Point3(-2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsEasy,
  'battleCell': BattleCellId2,
  'pos': Point3(2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.BossbotCogGolfCouseCogLevelsEasy,
  'battleCell': BattleCellId2,
  'pos': Point3(6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]

ReserveCogData = []
