from toontown.coghq.SpecImports import *
from toontown.toonbase import ToontownGlobals
import random

CogParent3 = 1043
BattleCellId3 = 2

CogParent = 1042
BattleCellId = 1

CogParent2 = 1041
BattleCellId2 = 0

BattleCells = {BattleCellId: {'parentEntId': CogParent,
                'pos': Point3(0, 0, 0)},
              BattleCellId2 : {'parentEntId': CogParent2,
                'pos': Point3(0, 0, 0)},
              BattleCellId3 : {'parentEntId': CogParent3,
                'pos': Point3(0, 0, 0)},
              }

CogData = [
  {"parentEntId": CogParent3,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsHard(),
  'battleCell': BattleCellId3,
  'pos': Point3(-6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {"parentEntId": CogParent3,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId3,
  'pos': Point3(-2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent3,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId3,
  'pos': Point3(2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  {"parentEntId": CogParent3,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId3,
  'pos': Point3(6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  
  {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsHard(),
  'battleCell': BattleCellId2,
  'pos': Point3(-6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId2,
  'pos': Point3(-2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId2,
  'pos': Point3(2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  {"parentEntId": CogParent2,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId2,
  'pos': Point3(6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
  
  {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsHard(),
  'battleCell': BattleCellId,
  'pos': Point3(-6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId,
  'pos': Point3(-2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId,
  'pos': Point3(2.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
  {"parentEntId": CogParent,
  "boss": 0,
  "skeleton": 0,
  'level': ToontownGlobals.LawbotDAOfficeCogLevelsEasy(),
  'battleCell': BattleCellId,
  'pos': Point3(6.0, 0.0, 0.0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]

ReserveCogData = []
